# Generated by Django 5.0 on 2023-12-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoxStoreApp', '0002_boxmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='constraints',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('A1', models.IntegerField()),
                ('V1', models.IntegerField()),
                ('L1', models.IntegerField()),
                ('L2', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'constraints',
            },
        ),
    ]
