# Generated by Django 5.0 on 2023-12-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoxStoreApp', '0003_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constraints',
            name='A1',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='constraints',
            name='L1',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='constraints',
            name='L2',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='constraints',
            name='V1',
            field=models.IntegerField(default=1000),
        ),
    ]
